public enum Commands {
    AUTH_REQUEST,
    AUTH_OK,
    AUTH_ERROR,
    GET_CLOUD_DIR_TREE,
    FILE_TRANSFER_SUCCESS,
    FILE_TRANSFER_ERROR,
    DELETE_FILE,
    DELETE_FILE_SUCCESS,
    DELETE_FILE_ERROR,
    DOWNLOAD_FILE,
    DOWNLOAD_FILE_SUCCESS,
    DOWNLOAD_FILE_ERROR,
    UPDATE_LISTS,

}
